print("Name : Sameer\nClass : M.Sc(IT) - 3rd sem\n")
decimal = int(input("Enter a decimal number : "))
binary = bin(decimal)
octal = oct(decimal)
hexadecimal = hex(decimal)
print("Decimal : ", decimal)
print("Binary : ", binary[2:])
print("Octal : ", octal[2:])
print("Hexadecimal : ", hexadecimal[2:])